In [3]:
import numpy as np
%config IPCompleter.greedy=True

### From Python list

In [2]:
my_list = [4,6,3,6,9]
my_list

[4, 6, 3, 6, 9]

In [4]:
arr = np.array(my_list)

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros and ones

Generate arrays of zeros or ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [14]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## eye

Creates an identity matrix

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [24]:
np.random.rand(3)

array([0.97293482, 0.83134185, 0.67171437])

In [46]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [26]:
np.random.randn(2)

array([ 0.23421316, -0.72976569])

In [27]:
np.random.randn(5,5)

array([[-0.03421457, -0.21905114,  0.73383355, -0.1901922 , -1.19503563],
       [-0.85126953,  1.53868505, -0.21814568, -1.10449149, -0.07972389],
       [ 0.7648622 ,  0.66162205,  1.06147475, -1.68604777, -0.79517635],
       [-0.87094534,  1.13201117, -0.81608698,  0.50772224, -0.29540555],
       [-0.62529435,  0.67992146, -0.11712625, -0.21096764,  0.18040533]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [28]:
np.random.randint(1,100)

60

In [29]:
np.random.randint(1,100,10)

array([45, 69, 96, 65,  9, 58, 21, 65, 95, 51])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [30]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([18, 35, 34, 14, 46,  4, 44,  6, 26, 47])

## Reshape
Returns an array containing the same data with a new shape.
.reshape(...) . But the number of items should remain the same

In [33]:
np.random.rand(1,200).reshape(10,20)

array([[0.34278425, 0.15619152, 0.71762106, 0.37577835, 0.05727365,
        0.20194977, 0.84702416, 0.2352984 , 0.51418014, 0.46619665,
        0.04989045, 0.3055898 , 0.18625138, 0.10053385, 0.29765408,
        0.08203804, 0.05393091, 0.79674233, 0.06852499, 0.82515735],
       [0.74678012, 0.07377676, 0.2688332 , 0.11339978, 0.10292737,
        0.2022278 , 0.46757617, 0.33214479, 0.91824753, 0.64386839,
        0.60218481, 0.30204671, 0.41904413, 0.75456378, 0.82946165,
        0.38594166, 0.75199433, 0.48988022, 0.22925172, 0.45369888],
       [0.55476428, 0.06083578, 0.95929937, 0.32332264, 0.88308149,
        0.2270101 , 0.7487267 , 0.66562657, 0.08672935, 0.22539515,
        0.1219316 , 0.87808308, 0.82038634, 0.33672813, 0.69300862,
        0.80139362, 0.00673532, 0.3342362 , 0.8183767 , 0.56866212],
       [0.6720995 , 0.38237304, 0.21373831, 0.05280171, 0.45600667,
        0.82500005, 0.09745179, 0.15357873, 0.54040658, 0.05817046,
        0.67196199, 0.66092257, 0.47503902, 0

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [38]:
ranarr.max()

47

In [36]:
np.max(ranarr)

47

In [39]:
ranarr.argmax()

9

In [40]:
ranarr.argmin()

5

In [41]:
ranarr

array([18, 35, 34, 14, 46,  4, 44,  6, 26, 47])

In [43]:
t = ranarr.max(), ranarr.argmax()
t

(47, 9)

### dtype

You can also grab the data type of the object in the array:
arr.dtype

In [44]:
arr.dtype

dtype('int64')

In [45]:
ranarr.dtype

dtype('int64')

In [46]:
len(arr)

25

In [47]:
ranarr.shape

(10,)

In [51]:
ranarr.reshape(2,5).shape

(2, 5)

In [49]:
ranarr.dtype

dtype('int64')

In [50]:
ranarr.shape

(10,)

In [54]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])