# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = arr + 30

In [6]:
arr + arr2

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [7]:
arr * arr2

array([  0,  31,  64,  99, 136, 175, 216, 259, 304, 351])

In [16]:
arr3 = np.arange(0,10)#.reshape(2,5)
arr4 = np.arange(0,10)#.reshape(5,2)
arr5 = arr3 * arr4
arr5

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

- Addition and subtraction of two arrays arr + arr and arr - arr
- Multiplication of two arrays arr * arr
- Division of two arrays - Note: Gives a warning on division by zero rather than an error

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

- square root using np.sqrt
- exp e^ using np.exp
- max using np.max or can use arr.max() also
