# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [61]:
import numpy as np

In [24]:
#Creating sample array
arr = np.arange(0,11)

In [4]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

- Get a value at an index

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[4]

4

- Get a value in a range

In [15]:
arr[4:-2]
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[4:8]

array([4, 5, 6, 7])

In [16]:
arr[8:4:-1]

array([8, 7, 6, 5])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

- Set a value with index range broad cast a value.
- a[0:5] = 300

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr2 = arr
arr2[1:4]=100
arr2

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [22]:
arr2[:]=50
arr2

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr3 = arr[1:].reshape(2,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
arr3[1,4]

10

In [30]:
arr3[1][4]

10

In [31]:
arr3[1]

array([ 6,  7,  8,  9, 10])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [32]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr != (6 or 4 or 2)

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [48]:
arr != (4 | 2)

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [42]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
bool_arr = arr>4

In [44]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
sum(arr>4)

6

In [12]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
(arr>2)&(arr<8)&(arr!=6)

array([False, False,  True,  True,  True, False,  True, False, False,
       False])

In [60]:
arr>2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [58]:
(arr>2)+1

array([1, 1, 2, 2, 2, 2, 2, 2, 2, 2])

In [59]:
(arr>2)&(arr<8)+1

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [14]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])